dados = 'dados/brasil_estados.parquet'
    mapa = 'dados/brasil-states.geojon.txt'
    descritivas=[
        'Estado',
        'Região',
        'Sigla',
    ]
    continuas = [
        'População', 'Densidade Demográfica', 'Veículos',
        'IDEB EF', 'IDEB EM', 'Rendimento per Capita', 'Ocupação ',
        'Rendimentos Ocupação', 'IDH', 'Área', 'Área Urbana'
    ]