dados='dados/brasil_estados.parquet'
mapa='dados/brazil-states.geojson.txt'
descritivas=[
    'Estado',
    'Região',
    'Sigla'
]
continuas = [
    'População', 'Densidade Demográfica', 'Veículos',
    'IDEB EF', 'IDEB EM', 'Rendimento per Capita', 'Ocupação ',
    'Rendimentos Ocupação', 'IDH', 'Área', 'Área Urbana'
]